# Generated by Django 5.2.7 on 2025-10-17 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do eixo (ex: Liderança, Estratégia)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Código único do eixo (ex: LEADERSHIP)', max_length=50, unique=True)),
                ('order', models.IntegerField(help_text='Ordem de exibição', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do eixo de avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eixo de Avaliação',
                'verbose_name_plural': 'Eixos de Avaliação',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='axis',
            field=models.ForeignKey(blank=True, help_text='Eixo de avaliação ISO 56002', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='forms.evaluationaxis'),
        ),
    ]
