# Generated by Django 5.2.7 on 2025-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_evaluationaxis_question_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationaxis',
            name='max_score_by_size',
            field=models.JSONField(blank=True, default=dict, help_text="Pontuação máxima por porte de empresa (ex: {'PE': 10.0, 'PME': 9.0, ...})"),
        ),
    ]
