# Generated by Django 5.2.7 on 2025-10-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_evaluationaxis_max_score_by_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_obtained', models.FloatField(default=0, help_text='Pontuação obtida neste eixo')),
                ('max_score_possible', models.FloatField(default=0, help_text='Pontuação máxima possível para este eixo (baseada no porte da empresa)')),
                ('percentage', models.FloatField(default=0, help_text='Percentual de atingimento (score_obtained / max_score_possible * 100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axis', models.ForeignKey(help_text='Eixo de avaliação', on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='forms.evaluationaxis')),
                ('evaluation', models.ForeignKey(help_text='Avaliação relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='axis_scores', to='forms.innovationevaluation')),
            ],
            options={
                'verbose_name': 'Pontuação por Eixo',
                'verbose_name_plural': 'Pontuações por Eixo',
                'ordering': ['axis__order'],
                'unique_together': {('evaluation', 'axis')},
            },
        ),
    ]
