# Generated by Django 5.2.7 on 2025-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_axisscore_benchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationevaluation',
            name='ranking_average_score',
            field=models.FloatField(blank=True, help_text='Pontuação média do porte', null=True),
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='ranking_better_than_percentage',
            field=models.FloatField(blank=True, help_text='% de empresas superadas', null=True),
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='ranking_percentile',
            field=models.FloatField(blank=True, help_text='Percentil da pontuação', null=True),
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='ranking_position',
            field=models.IntegerField(blank=True, help_text='Posição no ranking', null=True),
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='ranking_top_score',
            field=models.FloatField(blank=True, help_text='Maior pontuação do porte', null=True),
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='ranking_total',
            field=models.IntegerField(blank=True, help_text='Total de avaliações no ranking', null=True),
        ),
    ]
