# Generated by Django 5.2.7 on 2025-10-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_innovationevaluation_ranking_average_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationevaluation',
            name='maturity_level',
        ),
        migrations.RemoveField(
            model_name='innovationevaluation',
            name='priority_action',
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='priority_action_fk',
            field=models.ForeignKey(blank=True, help_text='Ação prioritária recomendada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='forms.priorityaction'),
        ),
        migrations.CreateModel(
            name='InnovationLevelMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_size', models.CharField(choices=[('PE', 'Pequena Empresa (até R$ 4,8 milhões/ano)'), ('PME', 'Pequena Média Empresa (R$ 4,8 a R$ 10 milhões/ano)'), ('ME', 'Média Empresa (R$ 10 a R$ 100 milhões/ano)'), ('GE', 'Grande Empresa (R$ 100 a R$ 300 milhões/ano)'), ('GGE', 'Muito Grande Empresa (acima de R$ 300 milhões/ano)')], help_text='Porte da empresa', max_length=10)),
                ('action', models.TextField(help_text='Ação de manutenção recomendada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maturity_level', models.ForeignKey(help_text='Nível de maturidade relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_actions', to='forms.maturitylevel')),
            ],
            options={
                'verbose_name': 'Manutenção do Nível de Inovação',
                'verbose_name_plural': 'Manutenções do Nível de Inovação',
                'ordering': ['maturity_level', 'company_size'],
                'unique_together': {('maturity_level', 'company_size')},
            },
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='maintenance_action',
            field=models.ForeignKey(blank=True, help_text='Ação de manutenção recomendada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='forms.innovationlevelmaintenance'),
        ),
        migrations.CreateModel(
            name='SalesTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_size', models.CharField(choices=[('PE', 'Pequena Empresa (até R$ 4,8 milhões/ano)'), ('PME', 'Pequena Média Empresa (R$ 4,8 a R$ 10 milhões/ano)'), ('ME', 'Média Empresa (R$ 10 a R$ 100 milhões/ano)'), ('GE', 'Grande Empresa (R$ 100 a R$ 300 milhões/ano)'), ('GGE', 'Muito Grande Empresa (acima de R$ 300 milhões/ano)')], help_text='Porte da empresa', max_length=10)),
                ('action', models.TextField(help_text='Gatilho de venda recomendado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maturity_level', models.ForeignKey(help_text='Nível de maturidade relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='sales_triggers', to='forms.maturitylevel')),
            ],
            options={
                'verbose_name': 'Gatilho de Venda',
                'verbose_name_plural': 'Gatilhos de Venda',
                'ordering': ['maturity_level', 'company_size'],
                'unique_together': {('maturity_level', 'company_size')},
            },
        ),
        migrations.AddField(
            model_name='innovationevaluation',
            name='sales_trigger',
            field=models.ForeignKey(blank=True, help_text='Gatilho de venda recomendado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='forms.salestrigger'),
        ),
    ]
